/*
 Copyright 2014 David Salter

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */
package com.davidsalter.bootstrapcdn;

/**
 * JPanel implementing list of v3 upwards versions of Bootstrap.
 * 
 * @author david@developinjava.com 31-03-2014
 */
public class BootstrapVersionPanel extends javax.swing.JPanel {

    /**
     * Creates new form BootstrapVersionPanel
     */
    public BootstrapVersionPanel() {
        initComponents();
    }

    /**
     * Gets the selected version of Bootstrap in the format x.x.x, e.g. 3.1.1
     * @return The selected version.
     */
    public String getSelectedVersion() {
        return bootstrapVersionList.getSelectedValue().toString();
    }
    
    /**
     * Flag indicating whether the Bootstrap CSS file is to be linked to or not.
     * @return Flag - true when CSS is selected, false otherwise
     */
    public Boolean isCssSelected() {
        return linkToCssCheckBox.isSelected();
    }
    
    /**
     * Flag indicating whether the Bootstrap JS file is to be linked to or not.
     * @return Flag - true when JS is selected, false otherwise
     */
    public Boolean isJsSelected() {
        return linkToJsCheckBox.isSelected();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bootstrapVersionLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bootstrapVersionList = new javax.swing.JList();
        linkToJsCheckBox = new javax.swing.JCheckBox();
        linkToCssCheckBox = new javax.swing.JCheckBox();

        bootstrapVersionLabel.setText(org.openide.util.NbBundle.getMessage(BootstrapVersionPanel.class, "BootstrapVersionPanel.bootstrapVersionLabel.text")); // NOI18N

        bootstrapVersionList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "3.1.1", "3.1.0", "3.0.3", "3.0.2", "3.0.1", "3.0.0" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(bootstrapVersionList);

        linkToJsCheckBox.setSelected(true);
        linkToJsCheckBox.setText(org.openide.util.NbBundle.getMessage(BootstrapVersionPanel.class, "BootstrapVersionPanel.linkToJsCheckBox.text")); // NOI18N

        linkToCssCheckBox.setSelected(true);
        linkToCssCheckBox.setText(org.openide.util.NbBundle.getMessage(BootstrapVersionPanel.class, "BootstrapVersionPanel.linkToCssCheckBox.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(linkToCssCheckBox)
                    .addComponent(linkToJsCheckBox)
                    .addComponent(bootstrapVersionLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bootstrapVersionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(linkToCssCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(linkToJsCheckBox)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bootstrapVersionLabel;
    private javax.swing.JList bootstrapVersionList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox linkToCssCheckBox;
    private javax.swing.JCheckBox linkToJsCheckBox;
    // End of variables declaration//GEN-END:variables
}
